apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  # PostgreSQL needs persistent storage to keep data across Pod recreation.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
