apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-data
spec:
  # One node can mount this volume read-write at a time.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
