apiVersion: v1
kind: Service
metadata:
  name: pyapp
spec:
  selector:
    # Same label as the Deployment template above.
    app: pyapp
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
